name: invendory_managment
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # state managment
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.0.3
  # service Locater
  get_it: ^7.2.0
  # internet requsts
  dio: ^4.0.6
  # secure Storages
  flutter_secure_storage: ^5.0.2
  dartz: ^0.10.1
  injectable: ^1.5.3
  collection: 
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed:
  build_runner:
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
